name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LINES_OF_CODE: True
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_OS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
          SHOW_UPDATED_DATE: False
          IGNORED_REPOS: "Config"
